[TEST]
;test 4G function or not,true/false
lteTest_flag = true

;Threshold number of retests, interval 500ms, must >= 1.
;If the device reply time exceeds 500ms, the reply time will be taken as the interval time.
flash_retryNum = 5

;Threshold number of retests, interval 500ms, must >= 1.
;If the device reply time exceeds 500ms, the reply time will be taken as the interval time.
gSensor_retryNum = 5

;Actual voltage * 100,unit：V
volt_maxTh = 4850
volt_minTh = 4750
subVolt_maxTh = 420
subVolt_minTh = 300
;Threshold number of retests, interval 500ms, must >= 1.
;If the device reply time exceeds 500ms, the reply time will be taken as the interval time.
volt_retryNum = 5

;Threshold number of retests, interval 500ms, must >= 1.
;If the device reply time exceeds 500ms, the reply time will be taken as the interval time.
lteInfo_retryNum = 10

;4G CSQ threshold,0~31
csq_minTh = 10
;Threshold number of retests, interval 500ms, must >= 1.
;If the device reply time exceeds 500ms, the reply time will be taken as the interval time.
csq_retryNum = 120

;GPS useful stars threshold. if 0, default GPS test succeeded.
uStarNum_minTh = 3
;Threshold number of retests, interval 500ms, must >= 1
;If the device reply time exceeds 500ms, the reply time will be taken as the interval time.
uStarNum_retryNum = 360